version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    env_file: .env



