version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
       
  
volumes:
    db_data:  
